name: php-training
type: php
docroot: ""
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
omit_containers: ["db", "dba"]
hooks:
  post-start:
    - exec: ".ddev/init.sh"
